### ISSUE TITLE
Separator to use between a message identifier and value

### ISSUE THREAD

**Issue by eemeli** [eemeli/message-resource-wg#4]
Each message in a resource needs to be identifiable by some name. For legibility and ease of parsing, it may make sense to use some sigil to separate the identifier from the value. This choice should take into account the syntax used to represent messages, which may start with e.g. `let $foo = {$bar}`.

Possible solutions:
1. Use `:` → `key: let $foo = {$bar} {value}`.
1. Use `=` → `key = let $foo = {$bar} {value}`.
1. Use whitespace → `key let $foo = {$bar} {value}`.

**Comment by stasm** [comment]
(3) may be a viable solution if the entire message body is delimited, like I suggested in https://github.com/eemeli/message-resource-wg/issues/6#issuecomment-1256457631.

**Comment by eemeli** [comment]
PR #11 uses `=` as a separator between key and value.
